//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValisManager.clay.mysurveys {
    
    
    public partial class Design_Survey {
        
        /// <summary>
        /// EditSurveyTabs2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ValisManager.clay.controls.EditSurveyTabs EditSurveyTabs2;
        
        /// <summary>
        /// pagesSelector control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Valis.Core.Html.WebControls.VLDropDownList pagesSelector;
    }
}
